org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties
minecraft_version=26.1.1
minecraft_version_range=[26.1.1]
neo_version=26.1.1.0-beta

## Mod Properties

mod_id=stonechest
mod_name=Stone Chest
mod_url=https://www.curseforge.com/minecraft/mc-mods/stone-chest
mod_license=MIT
mod_issue_tracker=https://github.com/DoctorFTB/StoneChest/issues
mod_version=1.0.0
mod_group_id=ftblag.stonechest
mod_authors=FTB_lag
mod_description=Stone variations vanilla chests.
