org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=false

systemProp.net.minecraftforge.gradle.repo.recompile.fork=true
systemProp.net.minecraftforge.gradle.repo.recompile.fork.args=-Xmx5G

systemProp.net.minecraftforge.gradle.repo.attach=false


## Environment Properties

minecraft_version=1.21.11
minecraft_version_range=[1.21.11,1.22)
forge_version=61.0.5
forge_version_range=[61,)
loader_version_range=[61,)
mapping_channel=official
mapping_version=1.21.11


## Mod Properties

mod_id=stonechest
mod_name=Stone Chest
mod_url=https://www.curseforge.com/minecraft/mc-mods/stone-chest
mod_license=MIT
mod_issue_tracker=https://github.com/DoctorFTB/StoneChest/issues
mod_version=1.0.0
mod_group_id=ftblag.stonechest
mod_authors=FTB_lag
mod_description=Stone variations vanilla chests.
